appname = movimientos_arka_crud
PGuser = ${MOVIMIENTOS_ARKA_CRUD_PGUSER}
PGpass = ${MOVIMIENTOS_ARKA_CRUD_PGPASS}
PGhost = ${MOVIMIENTOS_ARKA_CRUD_PGURLS}
PGdb   = ${MOVIMIENTOS_ARKA_CRUD_PGDB}
PGschema = ${MOVIMIENTOS_ARKA_CRUD_SCHEMA}
runmode = ${MOVIMIENTOS_ARKA_CRUD_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
PGport = ${MOVIMIENTOS_ARKA_CRUD_PGPORT}
parameterStore = ${PARAMETER_STORE}
